menu_items = [
    {"MenuItemID": 1, "Name": "Bacon Cheeseburger", "Price": 8.29},
    {"MenuItemID": 2, "Name": "Classic Hamburger", "Price": 6.89},
    {"MenuItemID": 3, "Name": "Double Stack Burger", "Price": 9.99},
    {"MenuItemID": 5, "Name": "Gig Em Patty Melt", "Price": 7.59},
    {"MenuItemID": 7, "Name": "Black Bean Burger", "Price": 8.38},
    {"MenuItemID": 6, "Name": "Cheeseburger", "Price": 6.89},
    {"MenuItemID": 9, "Name": "Rev's Grilled Chicken Sandwich", "Price": 8.39},
    {"MenuItemID": 10, "Name": "Spicy Chicken Sandwich", "Price": 8.39},
    {"MenuItemID": 11, "Name": "Aggie Chicken Club", "Price": 8.39},
    {"MenuItemID": 12, "Name": "2 Corn Dog Value Meal", "Price": 4.99},
    {"MenuItemID": 13, "Name": "2 Hot Dog Value Meal", "Price": 4.99},
    {"MenuItemID": 14, "Name": "3 Tender Entree", "Price": 4.99},
    {"MenuItemID": 15, "Name": "3 Chicken Tender Combo", "Price": 7.99},
    {"MenuItemID": 16, "Name": "French Fries", "Price": 1.99},
    {"MenuItemID": 17, "Name": "Aggie Shakes", "Price": 4.49},
    {"MenuItemID": 18, "Name": "Cookie Ice Cream Sundae", "Price": 4.69},
    {"MenuItemID": 19, "Name": "Double Scoop Ice Cream", "Price": 3.29},
    {"MenuItemID": 20, "Name": "Root Beer Float", "Price": 5.49},
    {"MenuItemID": 21, "Name": "Fountain Drink", "Price": 1.99},
    {"MenuItemID": 22, "Name": "Bottled Water", "Price": 2.19}
]

ingredients_inventory = [
    {"IngredientID": 1, "Name": "Beef Patties",
        "Stock": 100, "MaxStock": 200, "Units": "Pieces"},
    {"IngredientID": 2, "Name": "Bacon", "Stock": 50,
        "MaxStock": 100, "Units": "Slices"},
    {"IngredientID": 3, "Name": "Cheddar Cheese",
        "Stock": 40, "MaxStock": 80, "Units": "Slices"},
    {"IngredientID": 4, "Name": "Lettuce",
        "Stock": 200, "MaxStock": 400, "Units": "Pieces"},
    {"IngredientID": 5, "Name": "Tomato", "Stock": 30,
        "MaxStock": 60, "Units": "Slices"},
    {"IngredientID": 6, "Name": "Onion", "Stock": 25,
        "MaxStock": 50, "Units": "Slices"},
    {"IngredientID": 7, "Name": "Pickles", "Stock": 15,
        "MaxStock": 30, "Units": "Slices"},
    {"IngredientID": 8, "Name": "Burger Buns",
        "Stock": 100, "MaxStock": 200, "Units": "Pieces"},
    {"IngredientID": 9, "Name": "Ketchup", "Stock": 1000,
        "MaxStock": 2000, "Units": "Pumps"},
    {"IngredientID": 10, "Name": "Mustard", "Stock": 1000,
        "MaxStock": 2000, "Units": "Pumps"},
    {"IngredientID": 11, "Name": "Texas Toast",
        "Stock": 50, "MaxStock": 100, "Units": "Slices"},
    {"IngredientID": 12, "Name": "Swiss Cheese",
        "Stock": 40, "MaxStock": 80, "Units": "Slices"},
    {"IngredientID": 13, "Name": "Black Bean Patty",
        "Stock": 50, "MaxStock": 100, "Units": "Pieces"},
    {"IngredientID": 14, "Name": "Avocado",
        "Stock": 20, "MaxStock": 40, "Units": "Pieces"},
    {"IngredientID": 15, "Name": "Spicy Mayo",
        "Stock": 500, "MaxStock": 1000, "Units": "Pumps"},
    {"IngredientID": 16, "Name": "Vegan Mayo",
        "Stock": 500, "MaxStock": 1000, "Units": "Pumps"},
    {"IngredientID": 17, "Name": "Chicken Breast",
        "Stock": 60, "MaxStock": 120, "Units": "Pieces"},
    {"IngredientID": 18, "Name": "Breaded Chicken Patty",
        "Stock": 60, "MaxStock": 120, "Units": "Pieces"},
    {"IngredientID": 19, "Name": "Cornmeal",
        "Stock": 10, "MaxStock": 20, "Units": "Bags"},
    {"IngredientID": 20, "Name": "Hot Dogs",
        "Stock": 50, "MaxStock": 100, "Units": "Pieces"},
    {"IngredientID": 21, "Name": "Hot Dog Buns",
        "Stock": 50, "MaxStock": 100, "Units": "Pieces"},
    {"IngredientID": 22, "Name": "Cooking Oil",
        "Stock": 20, "MaxStock": 40, "Units": "Liters"},
    {"IngredientID": 23, "Name": "Potatoes",
        "Stock": 30, "MaxStock": 60, "Units": "Pounds"},
    {"IngredientID": 24, "Name": "Ice Cream",
        "Stock": 50, "MaxStock": 100, "Units": "Pints"},
    {"IngredientID": 25, "Name": "Milk", "Stock": 20,
        "MaxStock": 40, "Units": "Gallons"},
    {"IngredientID": 26, "Name": "Flavor Syrup",
        "Stock": 10, "MaxStock": 20, "Units": "Bottles"},
    {"IngredientID": 27, "Name": "Chocolate Chip Cookies",
        "Stock": 30, "MaxStock": 60, "Units": "Packets"},
    {"IngredientID": 28, "Name": "Chocolate Syrup",
        "Stock": 5, "MaxStock": 10, "Units": "Bottles"},
    {"IngredientID": 29, "Name": "Whipped Cream",
        "Stock": 10, "MaxStock": 20, "Units": "Cans"},
    {"IngredientID": 30, "Name": "Root Beer",
        "Stock": 20, "MaxStock": 40, "Units": "Bottles"},
    {"IngredientID": 31, "Name": "Carbonated Water",
        "Stock": 250, "MaxStock": 500, "Units": "Liters"},
    {"IngredientID": 32, "Name": "Flavored Syrup",
        "Stock": 50, "MaxStock": 100, "Units": "Liters"},
    {"IngredientID": 33, "Name": "Water", "Stock": 100,
        "MaxStock": 200, "Units": "Bottles"},
    {"IngredientID": 34, "Name": "Gig Em Sauce", "Stock": 1000,
        "MaxStock": 2000, "Units": "Pumps"},
    {"IngredientID": 35, "Name": "Ranch", "Stock": 500,
        "MaxStock": 1000, "Units": "Pumps"},
    {"IngredientID": 36, "Name": "Buffalo Sauce", "Stock": 500,
        "MaxStock": 1000, "Units": "Pumps"},
    {"IngredientID": 40, "Name": "20 oz Cup/Lid", "Stock": 500,
        "MaxStock": 1000, "Units": "Pairs"},
    {"IngredientID": 41, "Name": "Togo Boxes", "Stock": 750,
        "MaxStock": 1500, "Units": "Boxes"},                
]


menu_item_ingredients = [
    # Ingredients for Bacon Cheeseburger
    {"MenuItemName": "Bacon Cheeseburger",
        "IngredientName": "Beef Patties", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Bacon Cheeseburger",
        "IngredientName": "Bacon", "Quantity": 4, "Units": "Slices"},
    {"MenuItemName": "Bacon Cheeseburger",
        "IngredientName": "Cheddar Cheese", "Quantity": 1, "Units": "Slices"},
    {"MenuItemName": "Bacon Cheeseburger",
        "IngredientName": "Burger Buns", "Quantity": 2, "Units": "Pieces"},

    # Ingredients for Classic Hamburger
    {"MenuItemName": "Classic Hamburger", 
     "IngredientName": "Beef Patties", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Classic Hamburger",
        "IngredientName": "Lettuce", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Classic Hamburger",
        "IngredientName": "Tomato", "Quantity": 2, "Units": "Slice"},
    {"MenuItemName": "Classic Hamburger",
        "IngredientName": "Onion", "Quantity": 3, "Units": "Slice"},
    {"MenuItemName": "Classic Hamburger",
        "IngredientName": "Pickle", "Quantity": 4, "Units": "Slice"},
    {"MenuItemName": "Classic Hamburger",
        "IngredientName": "Burger Buns", "Quantity": 2, "Units": "Pieces"},

    # Ingredients for Double Stack Burger
    {"MenuItemName": "Double Stack Burger",
        "IngredientName": "Beef Patties", "Quantity": 2, "Units": "Pieces"},
    {"MenuItemName": "Double Stack Burger",
        "IngredientName": "Cheddar Cheese", "Quantity": 2, "Units": "Slices"},
    {"MenuItemName": "Double Stack Burger",
        "IngredientName": "Burger Buns", "Quantity": 2, "Units": "Pieces"},

    # Ingredients for Patty Melt
    {"MenuItemName": "Gig Em Patty Melt", 
     "IngredientName": "Beef Patties", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Gig Em Patty Melt", 
        "IngredientName": "Swiss Cheese", "Quantity": 1, "Units": "Slices"},
    {"MenuItemName": "Gig Em Patty Melt",
        "IngredientName": "Onion", "Quantity": 3, "Units": "Slices"},
    {"MenuItemName": "Gig Em Patty Melt",
        "IngredientName": "Pickle", "Quantity": 4, "Units": "Slice"},
    {"MenuItemName": "Gig Em Patty Melt",
        "IngredientName": "Texas Toast", "Quantity": 2, "Units": "Pieces"},
    {"MenuItemName": "Gig Em Patty Melt", 
        "IngredientName": "Gig Em Sauce", "Quantity": 1, "Units": "Pumps"},

    # Ingredients for Black Bean Burger
    {"MenuItemName": "Black Bean Burger", 
        "IngredientName": "Black Bean Patties", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Black Bean Burger", 
        "IngredientName": "Lettuce", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Black Bean Burger", 
        "IngredientName": "Tomato", "Quantity": 2, "Units": "Slice"},
    {"MenuItemName": "Black Bean Burger", 
        "IngredientName": "Onion", "Quantity": 3, "Units": "Slice"},
    {"MenuItemName": "Black Bean Burger", 
        "IngredientName": "Pickle", "Quantity": 4, "Units": "Slice"},
    {"MenuItemName": "Black Bean Burger", 
        "IngredientName": "Burger Buns", "Quantity": 2, "Units": "Pieces"},

    # Ingredients for Cheeseburger
    {"MenuItemName": "Cheeseburger", 
     "IngredientName": "Beef Patties", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Cheeseburger",
        "IngredientName": "Cheddar Cheese", "Quantity": 1, "Units": "Slices"},
    {"MenuItemName": "Cheeseburger",
        "IngredientName": "Pickle", "Quantity": 4, "Units": "Slice"},
    {"MenuItemName": "Cheeseburger",
        "IngredientName": "Burger Buns", "Quantity": 2, "Units": "Pieces"},

    # Ingredients for Rev's Grilled Chicken Sandwich
    {"MenuItemName": "Rev's Grilled Chicken Sandwich", 
     "IngredientName": "Chicken Breast", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Rev's Grilled Chicken Sandwich",
        "IngredientName": "Lettuce", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Rev's Grilled Chicken Sandwich", 
        "IngredientName": "Tomato", "Quantity": 2, "Units": "Slice"},
    {"MenuItemName": "Rev's Grilled Chicken Sandwich", 
        "IngredientName": "Onion", "Quantity": 3, "Units": "Slice"},
    {"MenuItemName": "Rev's Grilled Chicken Sandwich", 
        "IngredientName": "Pickle", "Quantity": 4, "Units": "Slice"},
    {"MenuItemName": "Rev's Grilled Chicken Sandwich", 
        "IngredientName": "Burger Buns", "Quantity": 2, "Units": "Pieces"},

    # Ingredients for Spicy Chicken Sandwich
    {"MenuItemName": "Spicy Chicken Sandwich", 
     "IngredientName": "Breaded Chicken Patty", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Spicy Chicken Sandwich", 
        "IngredientName": "Lettuce", "Quantity": 3, "Units": "Pieces"},
    {"MenuItemName": "Spicy Chicken Sandwich", 
        "IngredientName": "Ranch", "Quantity": 1, "Units": "Pumps"},
    {"MenuItemName": "Spicy Chicken Sandwich", 
        "IngredientName": "Buffalo Sauce", "Quantity": 1, "Units": "Pumps"},
    {"MenuItemName": "Spicy Chicken Sandwich", 
        "IngredientName": "Burger Buns", "Quantity": 2, "Units": "Pieces"},

    # Ingredients for Aggie Chicken Club
    {"MenuItemName": "Aggie Chicken Club", 
     "IngredientName": "Breaded Chicken Patty", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Aggie Chicken Club", 
        "IngredientName": "Swiss Cheese", "Quantity": 1, "Units": "Slices"},
    {"MenuItemName": "Aggie Chicken Club", 
        "IngredientName": "Bacon", "Quantity": 3, "Units": "Slices"},
    {"MenuItemName": "Aggie Chicken Club",  # TODO: Change this to be .25
        "IngredientName": "Avocado", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Aggie Chicken Club",
        "IngredientName": "Burger Buns", "Quantity": 2, "Units": "Pieces"},

    # Ingredients for Fountain Drink
    {"MenutItemName": "Fountain Drink",
     "IngredientName": "Carbonated Water", "Quantity": .5, "Units": "Liters"},
    {"MenutItemName": "Fountain Drink",
     "IngredientName": "Flavored Syrup", "Quantity": .1, "Units": "Liters"},
    {"MenutItemName": "Fountain Drink",
     "IngredientName": "20 oz Cup/Lid", "Quantity": 1, "Units": "Pairs"},         

    # Ingredients for Bottled Water
    {"MenutItemName": "Bottled Water",
     "IngredientName": "Water", "Quantity": 1, "Units": "Bottles"}

    # Continue adding entries for each menu item and their ingredients...
]

# Lookup dictionary to convert Item Names to ID's for storage in database
menu_item_id_lookup = {item['Name']: item['MenuItemID'] for item in menu_items}
ingredient_id_lookup = {
    ingredient['Name']: ingredient['IngredientID'] for ingredient in ingredients_inventory}



