menu_items = [
    {"MenuItemID": 1, "Name": "Bacon Cheeseburger", "Price": 8.29},
    {"MenuItemID": 2, "Name": "Classic Hamburger", "Price": 6.89},
    {"MenuItemID": 3, "Name": "Double Stack Burger", "Price": 9.99},
    {"MenuItemID": 4, "Name": "Gig Em Patty Melt", "Price": 7.59},
    {"MenuItemID": 5, "Name": "Black Bean Burger", "Price": 8.38},
    {"MenuItemID": 6, "Name": "Cheeseburger", "Price": 6.89},
    {"MenuItemID": 7, "Name": "Rev's Grilled Chicken Sandwich", "Price": 8.39},
    {"MenuItemID": 8, "Name": "Spicy Chicken Sandwich", "Price": 8.39},
    {"MenuItemID": 9, "Name": "Aggie Chicken Club", "Price": 8.39},
    {"MenuItemID": 10, "Name": "2 Hot Dog Value Meal", "Price": 4.99},
    {"MenuItemID": 11, "Name": "2 Corn Dog Value Meal", "Price": 4.99},
    {"MenuItemID": 12, "Name": "3 Tender Entree", "Price": 4.99},
    {"MenuItemID": 13, "Name": "3 Chicken Tender Combo", "Price": 7.99},
    {"MenuItemID": 14, "Name": "French Fries", "Price": 1.99},
    {"MenuItemID": 15, "Name": "Cookie Ice Cream Sundae", "Price": 4.69},
    {"MenuItemID": 16, "Name": "Oreo Shake", "Price": 4.49},
    {"MenuItemID": 17, "Name": "Chocolate Shake", "Price": 4.49},
    {"MenuItemID": 18, "Name": "Strawberry Shake", "Price": 4.49},
    {"MenuItemID": 19, "Name": "Vanilla Shake", "Price": 4.49},
    {"MenuItemID": 20, "Name": "Chocolate Double Scoop Ice Cream", "Price": 3.29},
    {"MenuItemID": 21, "Name": "Peppermint Double Scoop Ice Cream", "Price": 3.29},
    {"MenuItemID": 22, "Name": "Strawberry Double Scoop Ice Cream", "Price": 3.29},
    {"MenuItemID": 23, "Name": "Vanilla Double Scoop Ice Cream", "Price": 3.29},
    {"MenuItemID": 24, "Name": "Oreo Cookie Double Scoop Ice Cream", "Price": 3.29},
    {"MenuItemID": 25, "Name": "Root Beer Float", "Price": 5.49},
    {"MenuItemID": 26, "Name": "Fountain Drink", "Price": 1.99},
    {"MenuItemID": 27, "Name": "Bottled Water", "Price": 2.19}
]

ingredients_inventory = [
    {"IngredientID": 1, "Name": "Beef Patties",
        "Stock": 100, "MaxStock": 200, "Units": "Pieces"},
    {"IngredientID": 2, "Name": "Bacon", "Stock": 50,
        "MaxStock": 100, "Units": "Slices"},
    {"IngredientID": 3, "Name": "Cheddar Cheese",
        "Stock": 40, "MaxStock": 80, "Units": "Slices"},
    {"IngredientID": 4, "Name": "Lettuce",
        "Stock": 200, "MaxStock": 400, "Units": "Pieces"},
    {"IngredientID": 5, "Name": "Tomato", "Stock": 30,
        "MaxStock": 60, "Units": "Slices"},
    {"IngredientID": 6, "Name": "Onion", "Stock": 25,
        "MaxStock": 50, "Units": "Slices"},
    {"IngredientID": 7, "Name": "Pickles", "Stock": 15,
        "MaxStock": 30, "Units": "Slices"},
    {"IngredientID": 8, "Name": "Burger Buns",
        "Stock": 100, "MaxStock": 200, "Units": "Pieces"},
    {"IngredientID": 9, "Name": "Ketchup", "Stock": 1000,
        "MaxStock": 2000, "Units": "Pumps"},
    {"IngredientID": 10, "Name": "Mustard", "Stock": 1000,
        "MaxStock": 2000, "Units": "Pumps"},
    {"IngredientID": 11, "Name": "Texas Toast",
        "Stock": 50, "MaxStock": 100, "Units": "Slices"},
    {"IngredientID": 12, "Name": "Swiss Cheese",
        "Stock": 40, "MaxStock": 80, "Units": "Slices"},
    {"IngredientID": 13, "Name": "Black Bean Patty",
        "Stock": 50, "MaxStock": 100, "Units": "Pieces"},
    {"IngredientID": 14, "Name": "Avocado",
        "Stock": 20, "MaxStock": 40, "Units": "Pieces"},
    {"IngredientID": 15, "Name": "Spicy Mayo",
        "Stock": 500, "MaxStock": 1000, "Units": "Pumps"},
    {"IngredientID": 16, "Name": "Vegan Mayo",
        "Stock": 500, "MaxStock": 1000, "Units": "Pumps"},
    {"IngredientID": 17, "Name": "Chicken Breast",
        "Stock": 60, "MaxStock": 120, "Units": "Pieces"},
    {"IngredientID": 18, "Name": "Breaded Chicken Patty",
        "Stock": 60, "MaxStock": 120, "Units": "Pieces"},
    {"IngredientID": 19, "Name": "Corndog",
        "Stock": 100, "MaxStock": 200, "Units": "Pieces"},
    {"IngredientID": 20, "Name": "Hot Dog",
        "Stock": 50, "MaxStock": 100, "Units": "Pieces"},
    {"IngredientID": 21, "Name": "Hot Dog Bun",
        "Stock": 50, "MaxStock": 100, "Units": "Pieces"},
    {"IngredientID": 22, "Name": "Cooking Oil",
        "Stock": 20, "MaxStock": 40, "Units": "Liters"},
    {"IngredientID": 23, "Name": "Potatoes",
        "Stock": 30, "MaxStock": 60, "Units": "Pounds"},
    {"IngredientID": 24, "Name": "Vanilla Ice Cream",
        "Stock": 50, "MaxStock": 100, "Units": "Pints"},
    {"IngredientID": 25, "Name": "Milk", "Stock": 20,
        "MaxStock": 40, "Units": "Gallons"},
    {"IngredientID": 26, "Name": "Bags",
        "Stock": 750, "MaxStock": 1500, "Units": "Bags"},
    {"IngredientID": 27, "Name": "Chocolate Chip Cookies",
        "Stock": 30, "MaxStock": 60, "Units": "Pieces"},
    {"IngredientID": 28, "Name": "Chocolate Ice Cream",
        "Stock": 50, "MaxStock": 100, "Units": "Pints"},
    {"IngredientID": 29, "Name": "Whipped Cream",
        "Stock": 10, "MaxStock": 20, "Units": "Cans"},
    {"IngredientID": 30, "Name": "Root Beer",
        "Stock": 50, "MaxStock": 100, "Units": "Bottles"},
    {"IngredientID": 31, "Name": "Carbonated Water",
        "Stock": 250, "MaxStock": 500, "Units": "Liters"},
    {"IngredientID": 32, "Name": "Flavored Syrup",
        "Stock": 50, "MaxStock": 100, "Units": "Liters"},
    {"IngredientID": 33, "Name": "Water", "Stock": 100,
        "MaxStock": 200, "Units": "Bottles"},
    {"IngredientID": 34, "Name": "Gig Em Sauce", "Stock": 1000,
        "MaxStock": 2000, "Units": "Pumps"},
    {"IngredientID": 35, "Name": "Ranch", "Stock": 500,
        "MaxStock": 1000, "Units": "Pumps"},
    {"IngredientID": 36, "Name": "Buffalo Sauce", "Stock": 500,
        "MaxStock": 1000, "Units": "Pumps"},
    {"IngredientID": 37, "Name": "Chicken Tender",
        "Stock": 60, "MaxStock": 120, "Units": "Pieces"},
    {"IngredientID": 38, "Name": "Strawberry Ice Cream",
        "Stock": 50, "MaxStock": 100, "Units": "Pints"},
    {"IngredientID": 39, "Name": "Peppermint Ice Cream",
        "Stock": 50, "MaxStock": 100, "Units": "Pints"},
    {"IngredientID": 40, "Name": "Oreo Ice Cream",
        "Stock": 50, "MaxStock": 100, "Units": "Pints"},
    {"IngredientID": 41, "Name": "20 oz Cup/Lid/Straw", "Stock": 500,
        "MaxStock": 1000, "Units": "Sets"},
    {"IngredientID": 42, "Name": "Togo Boxes", "Stock": 750,
        "MaxStock": 1500, "Units": "Boxes"},
    {"IngredientID": 43, "Name": "Napkins", "Stock": 1500,
        "MaxStock": 3000, "Units": "Napkins"},
    {"IngredientID": 44, "Name": "Utensil Sets", "Stock": 750,
        "MaxStock": 1500, "Units": "Sets"},
    {"IngredientID": 45, "Name": "Bowls", "Stock": 250,
        "MaxStock": 500, "Units": "Bowls"},
]

menu_item_ingredients = [
    # Ingredients for Bacon Cheeseburger
    {"MenuItemName": "Bacon Cheeseburger",
        "IngredientName": "Beef Patties", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Bacon Cheeseburger",
        "IngredientName": "Bacon", "Quantity": 4, "Units": "Slices"},
    {"MenuItemName": "Bacon Cheeseburger",
        "IngredientName": "Cheddar Cheese", "Quantity": 1, "Units": "Slices"},
    {"MenuItemName": "Bacon Cheeseburger",
        "IngredientName": "Burger Buns", "Quantity": 2, "Units": "Pieces"},
    {"MenuItemName": "Bacon Cheeseburger",
        "IngredientName": "Togo Boxes", "Quantity": 1, "Units": "Boxes"},
    {"MenuItemName": "Bacon Cheeseburger",
        "IngredientName": "Napkins", "Quantity": 2, "Units": "Napkins"},
    {"MenuItemName": "Bacon Cheeseburger",
        "IngredientName": "Utensil Sets", "Quantity": 1, "Units": "Sets"},

    # Ingredients for Classic Hamburger
    {"MenuItemName": "Classic Hamburger",
     "IngredientName": "Beef Patties", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Classic Hamburger",
        "IngredientName": "Lettuce", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Classic Hamburger",
        "IngredientName": "Tomato", "Quantity": 2, "Units": "Slice"},
    {"MenuItemName": "Classic Hamburger",
        "IngredientName": "Onion", "Quantity": 3, "Units": "Slice"},
    {"MenuItemName": "Classic Hamburger",
        "IngredientName": "Pickles", "Quantity": 4, "Units": "Slice"},
    {"MenuItemName": "Classic Hamburger",
        "IngredientName": "Burger Buns", "Quantity": 2, "Units": "Pieces"},
    {"MenuItemName": "Classic Hamburger",
        "IngredientName": "Togo Boxes", "Quantity": 1, "Units": "Boxes"},
    {"MenuItemName": "Classic Hamburger",
        "IngredientName": "Napkins", "Quantity": 2, "Units": "Napkins"},
    {"MenuItemName": "Classic Hamburger",
        "IngredientName": "Utensil Sets", "Quantity": 1, "Units": "Sets"},

    # Ingredients for Double Stack Burger
    {"MenuItemName": "Double Stack Burger",
        "IngredientName": "Beef Patties", "Quantity": 2, "Units": "Pieces"},
    {"MenuItemName": "Double Stack Burger",
        "IngredientName": "Cheddar Cheese", "Quantity": 2, "Units": "Slices"},
    {"MenuItemName": "Double Stack Burger",
        "IngredientName": "Burger Buns", "Quantity": 2, "Units": "Pieces"},
    {"MenuItemName": "Double Stack Burger",
        "IngredientName": "Togo Boxes", "Quantity": 1, "Units": "Boxes"},
    {"MenuItemName": "Double Stack Burger",
        "IngredientName": "Napkins", "Quantity": 2, "Units": "Napkins"},
    {"MenuItemName": "Double Stack Burger",
        "IngredientName": "Utensil Sets", "Quantity": 1, "Units": "Sets"},

    # Ingredients for Patty Melt
    {"MenuItemName": "Gig Em Patty Melt",
     "IngredientName": "Beef Patties", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Gig Em Patty Melt",
        "IngredientName": "Swiss Cheese", "Quantity": 1, "Units": "Slices"},
    {"MenuItemName": "Gig Em Patty Melt",
        "IngredientName": "Onion", "Quantity": 3, "Units": "Slices"},
    {"MenuItemName": "Gig Em Patty Melt",
        "IngredientName": "Pickles", "Quantity": 4, "Units": "Slice"},
    {"MenuItemName": "Gig Em Patty Melt",
        "IngredientName": "Texas Toast", "Quantity": 2, "Units": "Pieces"},
    {"MenuItemName": "Gig Em Patty Melt",
        "IngredientName": "Gig Em Sauce", "Quantity": 1, "Units": "Pumps"},
    {"MenuItemName": "Gig Em Patty Melt",
        "IngredientName": "Togo Boxes", "Quantity": 1, "Units": "Boxes"},
    {"MenuItemName": "Gig Em Patty Melt",
        "IngredientName": "Napkins", "Quantity": 2, "Units": "Napkins"},
    {"MenuItemName": "Gig Em Patty Melt",
        "IngredientName": "Utensil Sets", "Quantity": 1, "Units": "Sets"},

    # Ingredients for Black Bean Burger
    {"MenuItemName": "Black Bean Burger",
        "IngredientName": "Black Bean Patty", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Black Bean Burger",
        "IngredientName": "Lettuce", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Black Bean Burger",
        "IngredientName": "Tomato", "Quantity": 2, "Units": "Slice"},
    {"MenuItemName": "Black Bean Burger",
        "IngredientName": "Onion", "Quantity": 3, "Units": "Slice"},
    {"MenuItemName": "Black Bean Burger",
        "IngredientName": "Pickles", "Quantity": 4, "Units": "Slice"},
    {"MenuItemName": "Black Bean Burger",
        "IngredientName": "Burger Buns", "Quantity": 2, "Units": "Pieces"},
    {"MenuItemName": "Black Bean Burger",
        "IngredientName": "Togo Boxes", "Quantity": 1, "Units": "Boxes"},
    {"MenuItemName": "Black Bean Burger",
        "IngredientName": "Napkins", "Quantity": 2, "Units": "Napkins"},
    {"MenuItemName": "Black Bean Burger",
        "IngredientName": "Utensil Sets", "Quantity": 1, "Units": "Sets"},

    # Ingredients for Cheeseburger
    {"MenuItemName": "Cheeseburger",
     "IngredientName": "Beef Patties", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Cheeseburger",
        "IngredientName": "Cheddar Cheese", "Quantity": 1, "Units": "Slices"},
    {"MenuItemName": "Cheeseburger",
        "IngredientName": "Pickles", "Quantity": 4, "Units": "Slice"},
    {"MenuItemName": "Cheeseburger",
        "IngredientName": "Burger Buns", "Quantity": 2, "Units": "Pieces"},
    {"MenuItemName": "Cheeseburger",
        "IngredientName": "Togo Boxes", "Quantity": 1, "Units": "Boxes"},
    {"MenuItemName": "Cheeseburger",
        "IngredientName": "Napkins", "Quantity": 2, "Units": "Napkins"},
    {"MenuItemName": "Cheeseburger",
        "IngredientName": "Utensil Sets", "Quantity": 1, "Units": "Sets"},

    # Ingredients for Rev's Grilled Chicken Sandwich
    {"MenuItemName": "Rev's Grilled Chicken Sandwich",
     "IngredientName": "Chicken Breast", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Rev's Grilled Chicken Sandwich",
        "IngredientName": "Lettuce", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Rev's Grilled Chicken Sandwich",
        "IngredientName": "Tomato", "Quantity": 2, "Units": "Slice"},
    {"MenuItemName": "Rev's Grilled Chicken Sandwich",
        "IngredientName": "Onion", "Quantity": 3, "Units": "Slice"},
    {"MenuItemName": "Rev's Grilled Chicken Sandwich",
        "IngredientName": "Pickles", "Quantity": 4, "Units": "Slice"},
    {"MenuItemName": "Rev's Grilled Chicken Sandwich",
        "IngredientName": "Burger Buns", "Quantity": 2, "Units": "Pieces"},
    {"MenuItemName": "Rev's Grilled Chicken Sandwich",
        "IngredientName": "Togo Boxes", "Quantity": 1, "Units": "Boxes"},
    {"MenuItemName": "Rev's Grilled Chicken Sandwich",
        "IngredientName": "Napkins", "Quantity": 2, "Units": "Napkins"},
    {"MenuItemName": "Rev's Grilled Chicken Sandwich",
        "IngredientName": "Utensil Sets", "Quantity": 1, "Units": "Sets"},

    # Ingredients for Spicy Chicken Sandwich
    {"MenuItemName": "Spicy Chicken Sandwich",
     "IngredientName": "Breaded Chicken Patty", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Spicy Chicken Sandwich",
        "IngredientName": "Lettuce", "Quantity": 3, "Units": "Pieces"},
    {"MenuItemName": "Spicy Chicken Sandwich",
        "IngredientName": "Ranch", "Quantity": 1, "Units": "Pumps"},
    {"MenuItemName": "Spicy Chicken Sandwich",
        "IngredientName": "Buffalo Sauce", "Quantity": 1, "Units": "Pumps"},
    {"MenuItemName": "Spicy Chicken Sandwich",
        "IngredientName": "Burger Buns", "Quantity": 2, "Units": "Pieces"},
    {"MenuItemName": "Spicy Chicken Sandwich",
        "IngredientName": "Togo Boxes", "Quantity": 1, "Units": "Boxes"},
    {"MenuItemName": "Spicy Chicken Sandwich",
        "IngredientName": "Napkins", "Quantity": 2, "Units": "Napkins"},
    {"MenuItemName": "Spicy Chicken Sandwich",
        "IngredientName": "Utensil Sets", "Quantity": 1, "Units": "Sets"},

    # Ingredients for Aggie Chicken Club
    {"MenuItemName": "Aggie Chicken Club",
     "IngredientName": "Breaded Chicken Patty", "Quantity": 1, "Units": "Pieces"},
    {"MenuItemName": "Aggie Chicken Club",
        "IngredientName": "Swiss Cheese", "Quantity": 1, "Units": "Slices"},
    {"MenuItemName": "Aggie Chicken Club",
        "IngredientName": "Bacon", "Quantity": 3, "Units": "Slices"},
    {"MenuItemName": "Aggie Chicken Club",
        "IngredientName": "Avocado", "Quantity": .25, "Units": "Pieces"},
    {"MenuItemName": "Aggie Chicken Club",
        "IngredientName": "Burger Buns", "Quantity": 2, "Units": "Pieces"},
    {"MenuItemName": "Aggie Chicken Club",
        "IngredientName": "Togo Boxes", "Quantity": 1, "Units": "Boxes"},
    {"MenuItemName": "Aggie Chicken Club",
        "IngredientName": "Napkins", "Quantity": 2, "Units": "Napkins"},
    {"MenuItemName": "Aggie Chicken Club",
        "IngredientName": "Utensil Sets", "Quantity": 1, "Units": "Sets"},

    # Ingredients for 2 Hot Dog Value Meal
    {"MenuItemName": "2 Hot Dog Value Meal",
     "IngredientName": "Hot Dog", "Quantity": 2, "Units": "Pieces"},
    {"MenuItemName": "2 Hot Dog Value Meal",
        "IngredientName": "Hot Dog Bun", "Quantity": 2, "Units": "Pieces"},
    {"MenuItemName": "2 Hot Dog Value Meal",
        "IngredientName": "Ketchup", "Quantity": 1, "Units": "Pumps"},
    {"MenuItemName": "2 Hot Dog Value Meal",
        "IngredientName": "Mustard", "Quantity": 1, "Units": "Pumps"},
    {"MenuItemName": "2 Hot Dog Value Meal",
        "IngredientName": "Togo Boxes", "Quantity": 1, "Units": "Boxes"},
    {"MenuItemName": "2 Hot Dog Value Meal",
        "IngredientName": "Napkins", "Quantity": 2, "Units": "Napkins"},
    {"MenuItemName": "2 Hot Dog Value Meal",
        "IngredientName": "Utensil Sets", "Quantity": 1, "Units": "Sets"},

    # Ingredients for 2 Corn Dog Value Meal
    {"MenuItemName": "2 Corn Dog Value Meal",
     "IngredientName": "Corndog", "Quantity": 2, "Units": "Pieces"},
    {"MenuItemName": "2 Corn Dog Value Meal",
        "IngredientName": "Ketchup", "Quantity": 1, "Units": "Pumps"},
    {"MenuItemName": "2 Corn Dog Value Meal",
        "IngredientName": "Mustard", "Quantity": 1, "Units": "Pumps"},
    {"MenuItemName": "2 Corn Dog Value Meal",
        "IngredientName": "Togo Boxes", "Quantity": 1, "Units": "Boxes"},
    {"MenuItemName": "2 Corn Dog Value Meal",
        "IngredientName": "Napkins", "Quantity": 2, "Units": "Napkins"},
    {"MenuItemName": "2 Corn Dog Value Meal",
        "IngredientName": "Utensil Sets", "Quantity": 1, "Units": "Sets"},

    # Ingredients for 3 Tender Entree
    {"MenuItemName": "3 Tender Entree",
     "IngredientName": "Chicken Tender", "Quantity": 3, "Units": "Pieces"},
    {"MenuItemName": "3 Tender Entree",
        "IngredientName": "Spicy Mayo", "Quantity": 1, "Units": "Pumps"},
    {"MenuItemName": "3 Tender Entree",
        "IngredientName": "Togo Boxes", "Quantity": 1, "Units": "Boxes"},
    {"MenuItemName": "3 Tender Entree",
        "IngredientName": "Napkins", "Quantity": 2, "Units": "Napkins"},
    {"MenuItemName": "3 Tender Entree",
        "IngredientName": "Utensil Sets", "Quantity": 1, "Units": "Sets"},

    # Ingredients for 3 Chicken Tender Combo
    {"MenuItemName": "3 Chicken Tender Combo",
     "IngredientName": "Chicken Tender", "Quantity": 3, "Units": "Pieces"},
    {"MenuItemName": "3 Chicken Tender Combo",
        "IngredientName": "Gig Em Sauce", "Quantity": 1, "Units": "Pumps"},
    {"MenuItemName": "3 Chicken Tender Combo",
     "IngredientName": "Potatoes", "Quantity": .25, "Units": "Pounds"},
    {"MenuItemName": "3 Chicken Tender Combo",
        "IngredientName": "Togo Boxes", "Quantity": 1, "Units": "Boxes"},
    {"MenuItemName": "3 Chicken Tender Combo",
        "IngredientName": "Napkins", "Quantity": 2, "Units": "Napkins"},
    {"MenuItemName": "3 Chicken Tender Combo",
        "IngredientName": "Utensil Sets", "Quantity": 1, "Units": "Sets"},
    {"MenuItemName": "3 Chicken Tender Combo",
        "IngredientName": "20 oz Cup/Lid/Straw", "Quantity": 1, "Units": "Sets"},

    # Ingredients for French Fries
    {"MenuItemName": "French Fries",
     "IngredientName": "Potatoes", "Quantity": .25, "Units": "Pounds"},
    {"MenuItemName": "French Fries",
        "IngredientName": "Togo Boxes", "Quantity": 1, "Units": "Boxes"},
    {"MenuItemName": "French Fries",
        "IngredientName": "Napkins", "Quantity": 2, "Units": "Napkins"},

    # Ingredients for Cookie Ice Cream Sundae
    {"MenuItemName": "Cookie Ice Cream Sundae",
        "IngredientName": "Chocolate Chip Cookies", "Quantity": 2, "Units": "Pieces"},
    {"MenuItemName": "Cookie Ice Cream Sundae",
        "IngredientName": "Vanilla Ice Cream", "Quantity": 0.125, "Units": "Pints"},
    {"MenuItemName": "Cookie Ice Cream Sundae",
        "IngredientName": "Togo Boxes", "Quantity": 1, "Units": "Boxes"},

    # Ingredients for Oreo Shake
    {"MenuItemName": "Oreo Shake",
        "IngredientName": "Oreo Ice Cream", "Quantity": 0.125, "Units": "Pints"},
    {"MenuItemName": "Oreo Shake",
        "IngredientName": "20 oz Cup/Lid/Straw", "Quantity": 1, "Units": "Sets"},

    # Ingredients for Chocolate Shake
    {"MenuItemName": "Chocolate Shake",
        "IngredientName": "Chocolate Ice Cream", "Quantity": 0.125, "Units": "Pints"},
    {"MenuItemName": "Chocolate Shake",
        "IngredientName": "20 oz Cup/Lid/Straw", "Quantity": 1, "Units": "Sets"},


    # Ingredients for Strawberry Shake
    {"MenuItemName": "Strawberry Shake",
        "IngredientName": "Strawberry Ice Cream", "Quantity": 0.125, "Units": "Pints"},
    {"MenuItemName": "Strawberry Shake",
        "IngredientName": "20 oz Cup/Lid/Straw", "Quantity": 1, "Units": "Sets"},

    # Ingredients for Vanilla Shake
    {"MenuItemName": "Vanilla Shake",
        "IngredientName": "Vanilla Ice Cream", "Quantity": 0.125, "Units": "Pints"},
    {"MenuItemName": "Vanilla Shake",
        "IngredientName": "20 oz Cup/Lid/Straw", "Quantity": 1, "Units": "Sets"},

    # Ingredients for Chocolate Double Scoop Ice Cream
    {"MenuItemName": "Chocolate Double Scoop Ice Cream",
     "IngredientName": "Chocolate Ice Cream", "Quantity": .5, "Units": "Pints"},
    {"MenuItemName": "Chocolate Double Scoop Ice Cream",
     "IngredientName": "Bowls", "Quantity": 1, "Units": "Bowls"},

    # Ingredients for Peppermint Double Scoop Ice Cream
    {"MenuItemName": "Peppermint Double Scoop Ice Cream",
     "IngredientName": "Peppermint Ice Cream", "Quantity": .5, "Units": "Pints"},
    {"MenuItemName": "Peppermint Double Scoop Ice Cream",
     "IngredientName": "Bowls", "Quantity": 1, "Units": "Bowls"},

    # Ingredients for Strawberry Double Scoop Ice Cream
    {"MenuItemName": "Strawberry Double Scoop Ice Cream",
        "IngredientName": "Strawberry Ice Cream", "Quantity": .5, "Units": "Pints"},
    {"MenuItemName": "Strawberry Double Scoop Ice Cream",
     "IngredientName": "Bowls", "Quantity": 1, "Units": "Bowls"},

    # Ingredients for Vanilla Double Scoop Ice Cream
    {"MenuItemName": "Vanilla Double Scoop Ice Cream",
        "IngredientName": "Vanilla Ice Cream", "Quantity": .5, "Units": "Pints"},
    {"MenuItemName": "Vanilla Double Scoop Ice Cream",
     "IngredientName": "Bowls", "Quantity": 1, "Units": "Bowls"},

    # Ingredients for Oreo Cookie Double Scoop Ice Cream
    {"MenuItemName": "Oreo Cookie Double Scoop Ice Cream",
        "IngredientName": "Oreo Ice Cream", "Quantity": .5, "Units": "Pints"},
    {"MenuItemName": "Oreo Cookie Double Scoop Ice Cream",
     "IngredientName": "Bowls", "Quantity": 1, "Units": "Bowls"},

    # Ingredients for Root Beer Float
    {"MenuItemName": "Root Beer Float",
        "IngredientName": "Vanilla Ice Cream", "Quantity": .5, "Units": "Pints"},
    {"MenuItemName": "Root Beer Float",
        "IngredientName": "20 oz Cup/Lid/Straw", "Quantity": 1, "Units": "Sets"},
    {"MenuItemName": "Root Beer Float",
        "IngredientName": "Root Beer", "Quantity": 1, "Units": "Bottles"},

    # Ingredients for Fountain Drink
    {"MenutItemName": "Fountain Drink",
     "IngredientName": "Carbonated Water", "Quantity": .5, "Units": "Liters"},
    {"MenutItemName": "Fountain Drink",
     "IngredientName": "Flavored Syrup", "Quantity": .1, "Units": "Liters"},
    {"MenutItemName": "Fountain Drink",
     "IngredientName": "20 oz Cup/Lid/Straw", "Quantity": 1, "Units": "Sets"},

    # Ingredients for Bottled Water
    {"MenuItemName": "Bottled Water",
        "IngredientName": "Water", "Quantity": 1, "Units": "Bottles"},
]

# Lookup dictionary to convert Item Names to ID's for storage in database
menu_item_id_lookup = {item['Name']: item['MenuItemID'] for item in menu_items}
ingredient_id_lookup = {
    ingredient['Name']: ingredient['IngredientID'] for ingredient in ingredients_inventory}
